version: '3.8'

services:
  app:
    container_name: leaseinsight_app
    build:
      context: .
    ports:
      - "8889:8080"
    depends_on:
      - postgres
      - redis
    restart: always
    command: mvn spring-boot:run
    environment:
      TZ: America/Sao_Paulo
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: ${JWT_SECRET}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      REDIS_TTL: ${REDIS_TTL}
      DB_URL_PROD: ${DB_URL_PROD}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      UPLOAD_DIR: ${UPLOAD_DIR}
    networks:
      - redis_network

  redis:
    container_name: redis_container
    image: redis:7.0.5-alpine
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
      - "6379:6379"
    networks:
      - redis_network

  postgres:
    container_name: postgres_container
    image: postgres:16.3
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge
