services:
  app:
    container_name: app_container
    environment:
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 587
      MAIL_USERNAME: 1c3dd26c8cdee3
      MAIL_PASSWORD: 9d0a3fc4036e40
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_TTL: 60
    image: raphaelmuniz/leaseinsight
    ports:
      - "8889:8889"
    depends_on:
      - db
      - redis
    restart: always
    command: mvn spring-boot:run
    build:
      context: .
    networks:
      - postgres-compose-network
  redis:
    container_name: redis_container
    image: redis:7.0.5-alpine
  postgres:
    container_name: postgres_container
    image: postgres:16.3
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leaseinsight_database
    ports:
      - "5000:5432"
    restart: always
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge